# -*- coding: utf-8 -*-
"""Text Summarization App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyMd3G2HdiFqg-DrG7hu5tQMKP2iAHLe

**Steps to Run**

Save the code as app.py.

Run the app using streamlit run app.py.

Input a paragraph and click "Summarize."
"""

# Install dependencies: pip install streamlit transformers
import streamlit as st
from transformers import pipeline

# Load summarization pipeline
summarizer = pipeline("summarization")

# Streamlit UI
st.title("Text Summarization App")
st.write("Paste your text below, and the app will generate a summary.")

# Input text
input_text = st.text_area("Enter text to summarize", height=200)

if st.button("Summarize"):
    if input_text.strip():
        summary = summarizer(input_text, max_length=50, min_length=25, do_sample=False)
        st.subheader("Summary:")
        st.write(summary[0]['summary_text'])
    else:
        st.warning("Please enter text to summarize.")