# -*- coding: utf-8 -*-
"""3. Image Caption Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyMd3G2HdiFqg-DrG7hu5tQMKP2iAHLe

3. **Image Caption Generator**

**Steps to Run**

Save the code as image_caption.py.

Run with streamlit run image_caption.py.

Upload an image and view the generated caption.
"""

# Install dependencies: pip install streamlit transformers
import streamlit as st
from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image

# Load BLIP model
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

# Streamlit UI
st.title("Image Caption Generator")
st.write("Upload an image, and the app will generate a caption.")

# File upload
uploaded_file = st.file_uploader("Choose an image", type=["jpg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)

    inputs = processor(images=image, return_tensors="pt")
    outputs = model.generate(**inputs)
    caption = processor.decode(outputs[0], skip_special_tokens=True)

    st.subheader("Generated Caption:")
    st.write(caption)